# Shell variables
# Generated by 'wal'
wallpaper='/home/linkio/Downloads/download.png'

# Special
background='#000000'
foreground='#ebebeb'
cursor='#ebebeb'

# Colors
color0='#000000'
color1='#575757'
color2='#666666'
color3='#777777'
color4='#8D8D8D'
color5='#ABABAB'
color6='#CDCDCD'
color7='#ebebeb'
color8='#a4a4a4'
color9='#575757'
color10='#666666'
color11='#777777'
color12='#8D8D8D'
color13='#ABABAB'
color14='#CDCDCD'
color15='#ebebeb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
