--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/linkio/Downloads/download.png"

-- Special
background="#000000"
foreground="#ebebeb"
cursor="#ebebeb"

-- Colors
color0="#000000"
color1="#575757"
color2="#666666"
color3="#777777"
color4="#8D8D8D"
color5="#ABABAB"
color6="#CDCDCD"
color7="#ebebeb"
color8="#a4a4a4"
color9="#575757"
color10="#666666"
color11="#777777"
color12="#8D8D8D"
color13="#ABABAB"
color14="#CDCDCD"
color15="#ebebeb"
